### ISSUE TITLE
Error while running pmca-console.py install

### ISSUE THREAD

**Issue by ymkim92** [ma1co/Sony-PMCA-RE#115] opened 2018-09-22 12:19 UTC
Windows 10 64bits and Python 3.7 64bits
Sony A6000 

I got this error:

```
(base) C:\Users\ykim\Downloads\Sony-PMCA-RE-0.17\Sony-PMCA-RE-0.17>pmca-console.py install
Traceback (most recent call last):
  File "C:\Users\ykim\Downloads\Sony-PMCA-RE-0.17\Sony-PMCA-RE-0.17\pmca-console.py", line 96, in <module>
    main()
  File "C:\Users\ykim\Downloads\Sony-PMCA-RE-0.17\Sony-PMCA-RE-0.17\pmca-console.py", line 72, in main
    installCommand(args.driver, args.apkFile, pkg, args.outFile, args.local)
  File "C:\Users\ykim\Downloads\Sony-PMCA-RE-0.17\Sony-PMCA-RE-0.17\pmca\commands\usb.py", line 271, in installCommand
    with importDriver(driverName) as driver:
  File "C:\Users\ykim\Downloads\Sony-PMCA-RE-0.17\Sony-PMCA-RE-0.17\pmca\commands\usb.py", line 159, in importDriver
    from ..usb.driver.windows.wpd import MtpContext
  File "C:\Users\ykim\Downloads\Sony-PMCA-RE-0.17\Sony-PMCA-RE-0.17\pmca\usb\driver\windows\wpd.py", line 25, in <module>
    GetModule('PortableDeviceApi.dll')
  File "C:\ProgramData\Miniconda3\lib\site-packages\comtypes\client\_generate.py", line 95, in GetModule
    tlib = comtypes.typeinfo.LoadTypeLibEx(tlib)
  File "C:\ProgramData\Miniconda3\lib\site-packages\comtypes\typeinfo.py", line 485, in LoadTypeLibEx
    _oleaut32.LoadTypeLibEx(c_wchar_p(szFile), regkind, byref(ptl))
  File "_ctypes/callproc.c", line 911, in GetResult
OSError: [WinError -2147312566] Error loading type library/DLL
```
Anybody helps me?

**Comment by ymkim92** [comment] 2018-09-23 05:38
Now I can run pmca-gui.py, but only in Ubuntu, not Windows.
I just follow the instruction at here: 
https://github.com/ma1co/Sony-PMCA-RE/pull/91/commits/8b745f5e8808475c272852cec190291378441518 

I don't know how to fix this problem in Windows

**Comment by ma1co** [comment] 2018-10-26 12:01
Duplicate of #105

**Closed by ma1co** 2018-10-26 12:01 UTC
