### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by denver009** [ma1co/Sony-PMCA-RE#247] opened 2021-07-08 21:35 UTC
HI CAN ANY ONE PUT SUPPORT FOR OLD ALPHA 68 CAMERA IN PMCA GUI..
SINCE IT IS NOT SUPPORTED..
I AM UNABLE TO REMOVE 29 MINUTE LIMIT ON IT,
PLEASE HELP..

**Comment by ma1co** [comment] 2021-08-12 10:06
Duplicate of #248

**Closed by ma1co** 2021-08-12 10:06 UTC
