### ISSUE TITLE
Always getting this error when i try to view camera details

### ISSUE THREAD

**Issue by cassera88** [ma1co/Sony-PMCA-RE#103] opened 2018-06-16 20:01 UTC
usb.core.USBError Erno13 Acess denied (insufficient permissions) when trying to view camera information or downloading the app

**Comment by benborman** [comment] 2018-06-19 01:15
I am also having this issue! @ma1co any insight? Seems to be several people experiencing this. Thanks!

**Comment by polynar** [comment] 2018-06-19 18:23
I am also having this issue!

**Comment by andydvsn** [comment] 2018-07-21 21:54
Just a nudge from me, same error, even with su privileges.
`usb.core.USBError: [Errno 13] Access denied (insufficient permissions)`
This is macOS 10.13.6.

**Comment by ma1co** [comment] 2018-10-26 12:29
Duplicate of #41. Please see my comment there.

**Closed by ma1co** 2018-10-26 12:29 UTC
