### ISSUE TITLE
A7RII (ILCE-7RM2) USB Connection -> PC Remote: Save images to SD Card

### ISSUE THREAD

**Issue by ltraveler** [ma1co/Sony-PMCA-RE#163] opened 2019-12-03 16:28 UTC
I have a **_Sony Alpha A7RII (ILCE-7RM2)_**.
I am trying to find a way of saving pictures that have been taken through the _PC Remote_ connection method on the _camera SD Card_ instead of sending them to the client application. Looks like by default the camera sending pictures to the client application and there is no way to save them to the SD Card by default.
Since _A7III (ILCE-7M3)_ came they have added an option to the menu system which is called **_PC Remote Settings_** and it has 2 options _PC_ or _PC + Camera_. 
Is that a way (firmware hack) to change default saving destination from client application to the SD Card through the PC Remote connection method?
I just bought a gimbal with the possibility to take pictures and record video using the gimbal buttons. Gimbal is connected to the camera through the PC Remote connection method, but I can only record video when I am trying to take a picture I can only make my camera focusing on the object there is no way to take a picture. So this hack gonna be very useful for people who have gimbals like **Zhiyun Weebill Lab** or **Zhiyun Weebill S**.

**Comment by ma1co** [comment] 2020-01-08 15:22
Duplicate of ma1co/OpenMemories-Tweak#357

**Closed by ma1co** 2020-01-08 15:22 UTC

**Comment by amauryverschooren** [comment] 2021-04-29 09:03
@ltraveler Have you got any more luck on this problem? I'm using the a7r ii for a timelpase and it is controlled by gphoto2. the only issue is that it doesn't save to the sd card while i'm giving it the command to do so in the gphoto2 script.

Did you found any solution for this problem?

**Comment by ltraveler** [comment] 2021-05-05 17:53
Unfortunately no luck.
But @ma1co mentioned OpenMemories Tweak #357 can't open it.
