### ISSUE TITLE
Cant install on a6500

### ISSUE THREAD

**Issue by quallsb72** [ma1co/Sony-PMCA-RE#102] opened 2018-06-15 22:58 UTC
usb.core.USBError Erno13 Acess denied (insufficient permissions)

**Comment by cassera88** [comment] 2018-06-16 21:08
i keep getting same error. Have you found any solutions. Mine camera is 7R2

**Comment by lapol** [comment] 2018-07-29 21:13
Try on different computer with Windows. Had the same problem on my Mac.

**Comment by ma1co** [comment] 2018-10-26 12:28
Duplicate of #41. Please see my comment there.

**Closed by ma1co** 2018-10-26 12:28 UTC
