### ISSUE TITLE
Open-Memory on A7R

### ISSUE THREAD

**Issue by mcsligo** [ma1co/Sony-PMCA-RE#19] opened 2016-08-18 20:09 UTC
Hi, Thanks for all your work! I have installed open memory tweak on my A7r but the video limit is still there. Any Ideas?

Thanks
Brian in Ireland

**Comment by ma1co** [comment] 2017-01-14 17:18
Duplicate of [this bug](https://github.com/ma1co/OpenMemories-Tweak/issues/15#issuecomment-230995129)

**Closed by ma1co** 2017-01-14 17:18 UTC
