### ISSUE TITLE
Release 0.15 GUI triggers chrome and windows virus protection

### ISSUE THREAD

**Issue by Bostwickenator** [ma1co/Sony-PMCA-RE#51] opened 2017-11-05 16:52 UTC
Chrome refuses to download the file and windows auto blocks it

**Comment by Bostwickenator** [comment] 2017-11-05 16:54
Looks like release 0.14 trips windows defender as well as "Trojan:win32/Tiggre!plock"

**Comment by dmwyatt** [comment] 2017-11-06 21:13
I had to go all the way back to .12 to find one that wasn't tripping the Chrome anti-virus and Windows Defender.

**Comment by ma1co** [comment] 2017-11-09 20:50
pmca-gui 0.15 should no longer trigger windows defender, I reported it successfully as a false positive. I'm not sure what to do about chrome though... You can get around the warning by opening the downloads list and clicking "Keep dangerous file".

**Comment by n0credit** [comment] 2017-11-11 21:44
How long does it takes for windows defender to update it´s database? As of today 0.15 still shows as Trojan:win32/Tiggre!rfn.

**Comment by ma1co** [comment] 2017-11-13 14:25
My bad, my windows defender seemed to accept it just temporarily. It should definitely be fixed now.

**Comment by myxious** [comment] 2017-11-19 10:29
Are all these results false-positive?
https://www.virustotal.com/ru/file/8041cfbbb23f724851748b3cea2a862ca712eae6eb0b90ce112e2e3576f5135b/analysis/

**Comment by ma1co** [comment] 2017-11-25 16:41
@myxious Basically yes. If you look at the reports, many of them are not very specific. The antivirus programs are probably triggered because we extract a lot of files. But this is inevitable with our current PyInstaller based builds...

I reported pmca-gui to a few of these companies as false-positives, so far all of them have confirmed that.

However, don't take the word of a random guy off the internet. The code is available in this repository. The builds are automatic. As long as you trust AppVeyor, PyInstaller und the code in this repo, you should be fine. And if you don't, you can always install python yourself and run the code directly from this repo.

**Closed** 2018-10-26 11:20 UTC
