### ISSUE TITLE
Please update support for WX500

### ISSUE THREAD

**Issue by ruzzty06** [ma1co/Sony-PMCA-RE#288] opened 2022-03-02 02:53 UTC
Hi, can you please add support for WX500? I already have the firmware from the camera based on your instructions. I uploaded it to ma1co's dropbox. My unit is Japanese though, not sure if will be a problem for you guys. My main purpose is to have English language to my unit.

**Comment by ma1co** [comment] 2022-03-03 21:30
Duplicate of #196

**Closed by ma1co** 2022-03-03 21:30 UTC
