### ISSUE TITLE
usb.core.USBError:[Erroro 13] Access Denied

### ISSUE THREAD

**Issue by neskuno** [ma1co/Sony-PMCA-RE#113] opened 2018-09-11 15:33 UTC
α7s2  ver 3.00

using PMCA-gui v0.17, but cannot instal OpenMemories:Tweak.

anybody same? help pls

**Comment by ellikeener** [comment] 2018-10-11 03:42
I'm experiencing the same issue. 

Is anyone able to address this? Please help 😅

**Comment by SergioCarabantes** [comment] 2018-10-14 01:34
same here

**Comment by Backpackstudio** [comment] 2018-10-21 11:29
What is your operating system?

**Comment by ma1co** [comment] 2018-10-26 12:29
Duplicate of #41. Please see my comment there.

**Closed by ma1co** 2018-10-26 12:29 UTC
