### ISSUE TITLE
Sony HDR-XR550V support please!

### ISSUE THREAD

**Issue by karak21** [ma1co/Sony-PMCA-RE#250] opened 2021-07-23 14:50 UTC
Please add support for the Sony HDR-XR550V.
Here is the device info:

Model:              HDR-XR550V  
Product code:       0002061440
Serial number:      00678622
Firmware version:   2.00
GPS Data:           2009-07-29 00:00:00 - 2009-08-28 00:00:00

**Comment by ma1co** [comment] 2021-08-12 10:27
This is a duplicate of [this issue](https://github.com/ma1co/OpenMemories-Tweak/issues/265). The camera is currently not supported, as it uses an unknown firmware encryption, but I have just posted some instructions on how to proceed. If you want to help, please continue the discussion there.

**Closed by ma1co** 2021-08-12 10:27 UTC
