### ISSUE TITLE
update OpenMemories-Tweak

### ISSUE THREAD

**Issue by neoshik** [ma1co/Sony-PMCA-RE#22] opened 2016-12-28 11:49 UTC
hello, can you please update OpenMemories-Tweak to work with rx100m5? 4K limit remover does not worh on rx100m5 https://github.com/ma1co/OpenMemories-Tweak/issues/130

**Comment by ma1co** [comment] 2017-01-14 17:15
Duplicate of the issue you linked to.

**Closed by ma1co** 2017-01-14 17:15 UTC
